theme: jekyll-theme-minimal
title: Chloe Chen
description: Welcome to my personal website. Here you can learn more about me as a person as well as find the most recent updates of my professional and academic career.
logo: /images/logo.jpg